spring.application.name=api
spring.jpa.hibernate.ddl-auto=update
spring.docker.compose.file=../docker-compose.yml
jwt.secret=esta_es_una_llave_secreta_muy_larga_para_que_jjwt_no_se_queje_12345


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE